# This is a basic workflow to help you get started with Actions

name: Run pkg2appimage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install desktop-file-utils
          wget https://github.com/AppImage/pkg2appimage/raw/master/pkg2appimage
          chmod +x pkg2appimage


      # Runs a set of commands using the runners shell
      - name: Run pkg2appimage
        run: |
          for yaml in *.yml
          do
            if [ "$yaml" == "PacketTracer-7.1.yml" ] ; then
              continue;
            fi

            echo "Running $yaml" 
            ./pkg2appimage $yaml
          done
